-- MySQL Script generated by MySQL Workbench
-- qua 02 abr 2025 10:50:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `telefone` INT NULL,
  `foto_de_perfil` VARCHAR(45) NULL,
  `numero_matricula` INT NOT NULL,
  `tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plano` (
  `idplano` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `duracao` VARCHAR(45) NULL,
  PRIMARY KEY (`idplano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`treino` (
  `idtreino` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `horario` TIME NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`idtreino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao_fisica` (
  `idavaliacao` INT NOT NULL AUTO_INCREMENT,
  `peso` DECIMAL(5,3) NOT NULL,
  `altura` DECIMAL(5,2) NOT NULL,
  `imc` DECIMAL(5,2) NOT NULL,
  `percentual_gordura` DECIMAL(5,2) NULL,
  `data_avaliacao` DATE NOT NULL,
  PRIMARY KEY (`idavaliacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`assinatura` (
  `idassinatura` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  PRIMARY KEY (`idassinatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
