FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install -g nodemon && npm install

# O volume do compose irá sobrescrever o que for copiado aqui, mas é importante
COPY ./codigo /app/

CMD ["nodemon", "--legacy-watch", "index.js"]