-- MySQL Script generated by MySQL Workbench
-- seg 08 set 2025 13:42:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gym_genesis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gym_genesis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gym_genesis` DEFAULT CHARACTER SET utf8 ;
USE `gym_genesis` ;

-- -----------------------------------------------------
-- Table `gym_genesis`.`alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`alimento` (
  `idalimento` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `calorias` DECIMAL(6,2) NOT NULL,
  `carboidratos` DECIMAL(6,2) NULL DEFAULT NULL,
  `proteinas` DECIMAL(6,2) NULL DEFAULT NULL,
  `gorduras` DECIMAL(6,2) NULL DEFAULT NULL,
  `porcao` VARCHAR(50) NULL DEFAULT NULL,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  `foto_de_perfil` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idalimento`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`plano` (
  `idplano` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `duracao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idplano`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `senha` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tipo_usuario` INT(1) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`assinatura` (
  `idassinatura` INT(11) NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `plano_id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idassinatura`),
  INDEX `idx_plano_id` (`plano_id` ASC) VISIBLE,
  INDEX `fk_assinatura_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_assinatura_plano`
    FOREIGN KEY (`plano_id`)
    REFERENCES `gym_genesis`.`plano` (`idplano`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_assinatura_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`cargo` (
  `idcargo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`funcionario` (
  `idfuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `data_contratacao` DATE NOT NULL,
  `salario` DECIMAL(10,2) NULL DEFAULT NULL,
  `cargo_id` INT(11) NULL DEFAULT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  INDEX `cargo_id` (`cargo_id` ASC) VISIBLE,
  INDEX `fk_funcionario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `funcionario_ibfk_1`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `gym_genesis`.`cargo` (`idcargo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`treino` (
  `idtreino` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `horario` TIME NOT NULL,
  `descricao` TEXT NOT NULL,
  `funcionario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idtreino`),
  INDEX `fk_treino_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_treino_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `gym_genesis`.`funcionario` (`idfuncionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`aula_agendada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`aula_agendada` (
  `idaula` INT(11) NOT NULL AUTO_INCREMENT,
  `data_aula` DATE NOT NULL,
  `dia_semana` ENUM('Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo') NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  `treino_id` INT(11) NOT NULL,
  `funcionario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idaula`),
  INDEX `fk_aula_agendada_treino1_idx` (`treino_id` ASC) VISIBLE,
  INDEX `fk_aula_agendada_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_aula_agendada_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `gym_genesis`.`funcionario` (`idfuncionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aula_agendada_treino1`
    FOREIGN KEY (`treino_id`)
    REFERENCES `gym_genesis`.`treino` (`idtreino`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`aula_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`aula_usuario` (
  `idaula` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idaula`, `usuario_id`),
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `aula_usuario_ibfk_1`
    FOREIGN KEY (`idaula`)
    REFERENCES `gym_genesis`.`aula_agendada` (`idaula`)
    ON DELETE CASCADE,
  CONSTRAINT `aula_usuario_ibfk_2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`avaliacao_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`avaliacao_fisica` (
  `idavaliacao` INT(11) NOT NULL AUTO_INCREMENT,
  `peso` DECIMAL(9,3) NOT NULL,
  `altura` DECIMAL(5,2) NOT NULL,
  `imc` DECIMAL(5,2) NOT NULL,
  `percentual_gordura` DECIMAL(5,2) NULL DEFAULT NULL,
  `data_avaliacao` DATE NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idavaliacao`),
  INDEX `fk_avaliacao_fisica_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_fisica_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`categoria_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`categoria_produto` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`cupom_desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`cupom_desconto` (
  `idcupom` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `percentual_desconto` DECIMAL(5,2) NULL DEFAULT NULL,
  `valor_desconto` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_validade` DATE NULL DEFAULT NULL,
  `quantidade_uso` INT(11) NULL DEFAULT 1,
  `tipo` ENUM('percentual', 'fixo') NULL DEFAULT 'percentual',
  PRIMARY KEY (`idcupom`),
  UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`dicas_nutricionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`dicas_nutricionais` (
  `iddicas_nutricionais` INT(11) NOT NULL AUTO_INCREMENT,
  `titulos` TEXT NOT NULL,
  `descricao` TEXT NOT NULL COMMENT 'texto maior da dica',
  `icone` TEXT NOT NULL COMMENT 'classe do ícone do FontAwesome',
  `cor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddicas_nutricionais`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`dieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`dieta` (
  `iddieta` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`iddieta`),
  INDEX `fk_dieta_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_dieta_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`refeicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`refeicao` (
  `idrefeicao` INT(11) NOT NULL AUTO_INCREMENT,
  `dieta_id` INT(11) NOT NULL,
  `tipo` ENUM('Café da manhã', 'Lanche da manhã', 'Almoço', 'Lanche da tarde', 'Jantar', 'Ceia') NOT NULL,
  `horario` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`idrefeicao`),
  INDEX `dieta_id` (`dieta_id` ASC) VISIBLE,
  CONSTRAINT `refeicao_ibfk_1`
    FOREIGN KEY (`dieta_id`)
    REFERENCES `gym_genesis`.`dieta` (`iddieta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`dieta_alimentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`dieta_alimentar` (
  `alimento_id` INT(11) NOT NULL,
  `refeicao_id` INT(11) NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  `observacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`alimento_id`, `refeicao_id`),
  INDEX `fk_alimento_has_refeicao_refeicao1_idx` (`refeicao_id` ASC) VISIBLE,
  INDEX `fk_alimento_has_refeicao_alimento1_idx` (`alimento_id` ASC) VISIBLE,
  CONSTRAINT `fk_alimento_has_refeicao_alimento1`
    FOREIGN KEY (`alimento_id`)
    REFERENCES `gym_genesis`.`alimento` (`idalimento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alimento_has_refeicao_refeicao1`
    FOREIGN KEY (`refeicao_id`)
    REFERENCES `gym_genesis`.`refeicao` (`idrefeicao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`endereco` (
  `idendereco` INT(11) NOT NULL AUTO_INCREMENT,
  `funcionario_id` INT(11) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `rua` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `complemento` VARCHAR(50) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  `usuario_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `funcionario_id` (`funcionario_id` ASC) VISIBLE,
  INDEX `fk_endereco_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `endereco_ibfk_2`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `gym_genesis`.`funcionario` (`idfuncionario`),
  CONSTRAINT `fk_endereco_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`exercicio` (
  `idexercicio` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `grupo_muscular` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `video_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idexercicio`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`forum` (
  `idtopico` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idtopico`),
  INDEX `fk_forum_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_forum_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`historico_peso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`historico_peso` (
  `idhistorico_peso` INT(11) NOT NULL AUTO_INCREMENT,
  `peso` DECIMAL(5,2) NOT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idhistorico_peso`),
  INDEX `fk_historico_peso_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_historico_peso_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`historico_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`historico_treino` (
  `idhistorico` INT(11) NOT NULL AUTO_INCREMENT,
  `treino_id` INT(11) NOT NULL,
  `data_execucao` DATETIME NOT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idhistorico`),
  INDEX `treino_id` (`treino_id` ASC) VISIBLE,
  INDEX `fk_historico_treino_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_historico_treino_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `historico_treino_ibfk_2`
    FOREIGN KEY (`treino_id`)
    REFERENCES `gym_genesis`.`treino` (`idtreino`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`pagamento` (
  `idpagamento` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `data_pagamento` DATETIME NOT NULL,
  `metodo` VARCHAR(45) NOT NULL,
  `status` ENUM('sucesso', 'falha', 'reembolsado') NULL DEFAULT 'sucesso',
  PRIMARY KEY (`idpagamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`pedido` (
  `idpedido` INT(11) NOT NULL AUTO_INCREMENT,
  `data_pedido` DATETIME NOT NULL,
  `status` ENUM('processando', 'enviado', 'concluído') NULL DEFAULT 'processando',
  `pagamento_id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_pagamento1_idx` (`pagamento_id` ASC) VISIBLE,
  INDEX `fk_pedido_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_pagamento1`
    FOREIGN KEY (`pagamento_id`)
    REFERENCES `gym_genesis`.`pagamento` (`idpagamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`produto` (
  `idproduto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `quantidade_estoque` INT(11) NOT NULL,
  `imagem` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`item_pedido` (
  `pedido_id` INT(11) NOT NULL,
  `produto_id` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`pedido_id`, `produto_id`),
  INDEX `fk_pedido_has_produto_produto1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_item`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `gym_genesis`.`pedido` (`idpedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produto_item`
    FOREIGN KEY (`produto_id`)
    REFERENCES `gym_genesis`.`produto` (`idproduto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`meta_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`meta_usuario` (
  `idmeta` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_limite` DATE NULL DEFAULT NULL,
  `status` ENUM('ativa', 'concluída', 'cancelada') NULL DEFAULT 'ativa',
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idmeta`),
  INDEX `fk_meta_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_meta_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`pagamento_detalhe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`pagamento_detalhe` (
  `idpagamento2` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('cartao', 'pix', 'boleto') NOT NULL,
  `bandeira_cartao` VARCHAR(30) NULL DEFAULT NULL,
  `ultimos_digitos` VARCHAR(4) NULL DEFAULT NULL,
  `codigo_pix` VARCHAR(255) NULL DEFAULT NULL,
  `linha_digitavel_boleto` VARCHAR(255) NULL DEFAULT NULL,
  `pagamento_id` INT(11) NOT NULL,
  PRIMARY KEY (`idpagamento2`),
  INDEX `fk_pagamento_detalhe_pagamento1_idx` (`pagamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_detalhe_pagamento1`
    FOREIGN KEY (`pagamento_id`)
    REFERENCES `gym_genesis`.`pagamento` (`idpagamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`perfil_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`perfil_professor` (
  `idperfil` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `foto_perfil` VARCHAR(255) NULL DEFAULT 'padrao.png',
  `modalidade` VARCHAR(50) NULL DEFAULT 'Presencial',
  `avaliacao_media` DECIMAL(3,2) NULL DEFAULT 0.00,
  `descricao` TEXT NULL DEFAULT '',
  `horarios_disponiveis` TEXT NULL DEFAULT '',
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idperfil`),
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `perfil_professor_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`perfil_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`perfil_usuario` (
  `idperfil_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `nome` VARCHAR(70) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `numero_matricula` VARCHAR(20) NOT NULL,
  `foto_perfil` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idperfil_usuario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `numero_matricula_UNIQUE` (`numero_matricula` ASC) VISIBLE,
  INDEX `fk_perfil_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`recuperacao_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`recuperacao_senha` (
  `idrecuperacao_senha` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(6) NOT NULL,
  `tempo_expiracao` DATETIME NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idrecuperacao_senha`),
  INDEX `fk_recuperacao_senha_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_recuperacao_senha_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`resposta_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`resposta_forum` (
  `idresposta` INT(11) NOT NULL AUTO_INCREMENT,
  `mensagem` TEXT NOT NULL,
  `data_resposta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `forum_id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idresposta`),
  INDEX `forum_id` (`forum_id` ASC) VISIBLE,
  INDEX `fk_resposta_forum_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_resposta_forum_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `resposta_forum_ibfk_2`
    FOREIGN KEY (`forum_id`)
    REFERENCES `gym_genesis`.`forum` (`idtopico`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`treino_exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`treino_exercicio` (
  `idtreino2` INT(11) NOT NULL AUTO_INCREMENT,
  `treino_id` INT(11) NOT NULL,
  `exercicio_id` INT(11) NOT NULL,
  `series` INT(11) NOT NULL,
  `repeticoes` INT(11) NOT NULL,
  `carga` DECIMAL(5,2) NULL DEFAULT NULL,
  `intervalo_segundos` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idtreino2`),
  INDEX `treino_id` (`treino_id` ASC) VISIBLE,
  INDEX `exercicio_id` (`exercicio_id` ASC) VISIBLE,
  CONSTRAINT `treino_exercicio_ibfk_1`
    FOREIGN KEY (`treino_id`)
    REFERENCES `gym_genesis`.`treino` (`idtreino`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `treino_exercicio_ibfk_2`
    FOREIGN KEY (`exercicio_id`)
    REFERENCES `gym_genesis`.`exercicio` (`idexercicio`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
