-- MySQL Script generated by MySQL Workbench
-- qui 24 abr 2025 09:51:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gym_genesis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gym_genesis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gym_genesis` DEFAULT CHARACTER SET utf8 ;
USE `gym_genesis` ;

-- -----------------------------------------------------
-- Table `gym_genesis`.`alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`alimento` (
  `idalimento` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `calorias` DECIMAL(6,2) NOT NULL,
  `carboidratos` DECIMAL(6,2) NULL DEFAULT NULL,
  `proteinas` DECIMAL(6,2) NULL DEFAULT NULL,
  `gorduras` DECIMAL(6,2) NULL DEFAULT NULL,
  `porcao` VARCHAR(50) NULL DEFAULT NULL,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idalimento`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `foto_de_perfil` VARCHAR(100) NULL DEFAULT NULL,
  `numero_matricula` VARCHAR(20) NOT NULL,
  `tipo_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`plano` (
  `idplano` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `duracao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idplano`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`assinatura` (
  `idassinatura` INT(11) NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  `plano_idplano` INT(11) NOT NULL,
  PRIMARY KEY (`idassinatura`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_assinatura_plano1_idx` (`plano_idplano` ASC) VISIBLE,
  CONSTRAINT `assinatura_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_assinatura_plano1`
    FOREIGN KEY (`plano_idplano`)
    REFERENCES `gym_genesis`.`plano` (`idplano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`aula_agendada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`aula_agendada` (
  `idaula` INT(11) NOT NULL AUTO_INCREMENT,
  `data_aula` DATE NOT NULL,
  `dia_semana` ENUM('Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo') NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idaula`),
  INDEX `fk_aula_agendada_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_aula_agendada_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`avaliacao_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`avaliacao_fisica` (
  `idavaliacao` INT(11) NOT NULL AUTO_INCREMENT,
  `peso` DECIMAL(5,3) NOT NULL,
  `altura` DECIMAL(5,2) NOT NULL,
  `imc` DECIMAL(5,2) NOT NULL,
  `percentual_gordura` DECIMAL(5,2) NULL DEFAULT NULL,
  `data_avaliacao` DATE NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idavaliacao`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `avaliacao_fisica_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`cargo` (
  `idcargo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`categoria_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`categoria_produto` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`cupom_desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`cupom_desconto` (
  `idcupom` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `percentual_desconto` DECIMAL(5,2) NULL DEFAULT NULL,
  `valor_desconto` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_validade` DATE NULL DEFAULT NULL,
  `quantidade_uso` INT(11) NULL DEFAULT 1,
  `tipo` ENUM('percentual', 'fixo') NULL DEFAULT 'percentual',
  PRIMARY KEY (`idcupom`),
  UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`dieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`dieta` (
  `iddieta` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`iddieta`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `dieta_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`refeicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`refeicao` (
  `idrefeicao` INT(11) NOT NULL AUTO_INCREMENT,
  `dieta_id` INT(11) NOT NULL,
  `tipo` ENUM('Café da manhã', 'Lanche da manhã', 'Almoço', 'Lanche da tarde', 'Jantar', 'Ceia') NOT NULL,
  `horario` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`idrefeicao`),
  INDEX `dieta_id` (`dieta_id` ASC) VISIBLE,
  CONSTRAINT `refeicao_ibfk_1`
    FOREIGN KEY (`dieta_id`)
    REFERENCES `gym_genesis`.`dieta` (`iddieta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`dieta_alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`dieta_alimento` (
  `iddieta_alimentar` INT(11) NOT NULL AUTO_INCREMENT,
  `refeicao_id` INT(11) NOT NULL,
  `alimento_id` INT(11) NOT NULL,
  `quantidade` DECIMAL(6,2) NOT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`iddieta_alimentar`),
  INDEX `refeicao_id` (`refeicao_id` ASC) VISIBLE,
  INDEX `alimento_id` (`alimento_id` ASC) VISIBLE,
  CONSTRAINT `dieta_alimento_ibfk_1`
    FOREIGN KEY (`refeicao_id`)
    REFERENCES `gym_genesis`.`refeicao` (`idrefeicao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `dieta_alimento_ibfk_2`
    FOREIGN KEY (`alimento_id`)
    REFERENCES `gym_genesis`.`alimento` (`idalimento`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`funcionario` (
  `idfuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `data_contratacao` DATE NOT NULL,
  `salario` DECIMAL(10,2) NULL DEFAULT NULL,
  `cargo_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `cargo_id` (`cargo_id` ASC) VISIBLE,
  CONSTRAINT `funcionario_ibfk_1`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `gym_genesis`.`cargo` (`idcargo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`endereco` (
  `idendereco` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NULL DEFAULT NULL,
  `funcionario_id` INT(11) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `rua` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `complemento` VARCHAR(50) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `funcionario_id` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `endereco_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `endereco_ibfk_2`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `gym_genesis`.`funcionario` (`idfuncionario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`exercicio` (
  `idexercicio` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `grupo_muscular` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `video_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idexercicio`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`forum` (
  `idtopico` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idtopico`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `forum_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`treino` (
  `idtreino` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `horario` TIME NOT NULL,
  `descricao` TEXT NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idtreino`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `treino_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`historico_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`historico_treino` (
  `idhistorico` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `treino_id` INT(11) NOT NULL,
  `data_execucao` DATETIME NOT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idhistorico`),
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `treino_id` (`treino_id` ASC) VISIBLE,
  CONSTRAINT `historico_treino_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `historico_treino_ibfk_2`
    FOREIGN KEY (`treino_id`)
    REFERENCES `gym_genesis`.`treino` (`idtreino`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`meta_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`meta_usuario` (
  `idmeta` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `descricao` TEXT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_limite` DATE NULL DEFAULT NULL,
  `status` ENUM('ativa', 'concluída', 'cancelada') NULL DEFAULT 'ativa',
  PRIMARY KEY (`idmeta`),
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `meta_usuario_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`pagamento` (
  `idpagamento` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `data_pagamento` DATETIME NOT NULL,
  `metodo` VARCHAR(45) NOT NULL,
  `status` ENUM('sucesso', 'falha', 'reembolsado') NULL DEFAULT 'sucesso',
  PRIMARY KEY (`idpagamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`pagamento_detalhe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`pagamento_detalhe` (
  `idpagamento2` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('cartao', 'pix', 'boleto') NOT NULL,
  `bandeira_cartao` VARCHAR(30) NULL DEFAULT NULL,
  `ultimos_digitos` VARCHAR(4) NULL DEFAULT NULL,
  `codigo_pix` VARCHAR(255) NULL DEFAULT NULL,
  `linha_digitavel_boleto` VARCHAR(255) NULL DEFAULT NULL,
  `pagamento_idpagamento` INT(11) NOT NULL,
  PRIMARY KEY (`idpagamento2`),
  INDEX `fk_pagamento_detalhe_pagamento1_idx` (`pagamento_idpagamento` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_detalhe_pagamento1`
    FOREIGN KEY (`pagamento_idpagamento`)
    REFERENCES `gym_genesis`.`pagamento` (`idpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`pedido` (
  `idpedido` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT(11) NOT NULL,
  `data_pedido` DATETIME NOT NULL,
  `status` ENUM('processando', 'enviado', 'concluído') NULL DEFAULT 'processando',
  `pagamento_idpagamento` INT(11) NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_pedido_pagamento1_idx` (`pagamento_idpagamento` ASC) VISIBLE,
  CONSTRAINT `pedido_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_pagamento1`
    FOREIGN KEY (`pagamento_idpagamento`)
    REFERENCES `gym_genesis`.`pagamento` (`idpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`produto` (
  `idproduto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `quantidade_estoque` INT(11) NOT NULL,
  `imagem` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`resposta_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`resposta_forum` (
  `idresposta` INT(11) NOT NULL AUTO_INCREMENT,
  `mensagem` TEXT NOT NULL,
  `data_resposta` DATETIME NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  `forum_idtopico` INT(11) NOT NULL,
  PRIMARY KEY (`idresposta`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `forum_idtopico` (`forum_idtopico` ASC) VISIBLE,
  CONSTRAINT `resposta_forum_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `resposta_forum_ibfk_2`
    FOREIGN KEY (`forum_idtopico`)
    REFERENCES `gym_genesis`.`forum` (`idtopico`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`treino_exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`treino_exercicio` (
  `idtreino2` INT(11) NOT NULL AUTO_INCREMENT,
  `treino_id` INT(11) NOT NULL,
  `exercicio_id` INT(11) NOT NULL,
  `series` INT(11) NOT NULL,
  `repeticoes` INT(11) NOT NULL,
  `carga` DECIMAL(5,2) NULL DEFAULT NULL,
  `intervalo_segundos` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idtreino2`),
  INDEX `treino_id` (`treino_id` ASC) VISIBLE,
  INDEX `exercicio_id` (`exercicio_id` ASC) VISIBLE,
  CONSTRAINT `treino_exercicio_ibfk_1`
    FOREIGN KEY (`treino_id`)
    REFERENCES `gym_genesis`.`treino` (`idtreino`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `treino_exercicio_ibfk_2`
    FOREIGN KEY (`exercicio_id`)
    REFERENCES `gym_genesis`.`exercicio` (`idexercicio`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`pedido_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`pedido_has_produto` (
  `pedido_idpedido` INT(11) NOT NULL,
  `produto_idproduto` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`pedido_idpedido`, `produto_idproduto`),
  INDEX `fk_pedido_has_produto_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_produto_pedido1`
    FOREIGN KEY (`pedido_idpedido` , `produto_idproduto`)
    REFERENCES `gym_genesis`.`pedido` (`idpedido` , `idpedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_has_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `gym_genesis`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`pagamento_assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`pagamento_assinatura` (
  `idpagamento` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `data_pagamento` DATETIME NOT NULL,
  `metodo` VARCHAR(45) NOT NULL,
  `status` ENUM('sucesso', 'falha', 'reembolsado') NULL DEFAULT 'sucesso',
  `assinatura_idassinatura` INT(11) NOT NULL,
  PRIMARY KEY (`idpagamento`),
  INDEX `fk_pagamento_assinatura_assinatura1_idx` (`assinatura_idassinatura` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_assinatura_assinatura1`
    FOREIGN KEY (`assinatura_idassinatura`)
    REFERENCES `gym_genesis`.`assinatura` (`idassinatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`pagamento_detalhe_assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`pagamento_detalhe_assinatura` (
  `idpagamento2` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('cartao', 'pix', 'boleto') NOT NULL,
  `bandeira_cartao` VARCHAR(30) NULL DEFAULT NULL,
  `ultimos_digitos` VARCHAR(4) NULL DEFAULT NULL,
  `codigo_pix` VARCHAR(255) NULL DEFAULT NULL,
  `linha_digitavel_boleto` VARCHAR(255) NULL DEFAULT NULL,
  `pagamento_idpagamento` INT(11) NOT NULL,
  PRIMARY KEY (`idpagamento2`),
  INDEX `fk_pagamento_detalhe_pagamento1_idx` (`pagamento_idpagamento` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_detalhe_pagamento10`
    FOREIGN KEY (`pagamento_idpagamento`)
    REFERENCES `gym_genesis`.`pagamento_assinatura` (`idpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gym_genesis`.`recuperacao_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_genesis`.`recuperacao_senha` (
  `idrecuperacao_senha` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idrecuperacao_senha`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_recuperacao_senha_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_recuperacao_senha_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `gym_genesis`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
