-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 19:56:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alimento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `calorias` DECIMAL(6,2) NOT NULL,
  `carboidratos` DECIMAL(6,2) NULL DEFAULT NULL,
  `proteinas` DECIMAL(6,2) NULL DEFAULT NULL,
  `gorduras` DECIMAL(6,2) NULL DEFAULT NULL,
  `porcao` VARCHAR(50) NULL DEFAULT NULL,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `foto_de_perfil` VARCHAR(100) NULL DEFAULT NULL,
  `numero_matricula` VARCHAR(20) NOT NULL,
  `tipo_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`assinatura` (
  `idassinatura` INT(11) NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idassinatura`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `assinatura_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horario` (
  `idhorario` INT(11) NOT NULL AUTO_INCREMENT,
  `dia_semana` ENUM('Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo') NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  PRIMARY KEY (`idhorario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`aula_agendada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aula_agendada` (
  `idaula` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT(11) NOT NULL,
  `horario_idhorario` INT(11) NOT NULL,
  `data_aula` DATE NOT NULL,
  PRIMARY KEY (`idaula`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `horario_idhorario` (`horario_idhorario` ASC) VISIBLE,
  CONSTRAINT `aula_agendada_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`),
  CONSTRAINT `aula_agendada_ibfk_2`
    FOREIGN KEY (`horario_idhorario`)
    REFERENCES `mydb`.`horario` (`idhorario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao_fisica` (
  `idavaliacao` INT(11) NOT NULL AUTO_INCREMENT,
  `peso` DECIMAL(5,3) NOT NULL,
  `altura` DECIMAL(5,2) NOT NULL,
  `imc` DECIMAL(5,2) NOT NULL,
  `percentual_gordura` DECIMAL(5,2) NULL DEFAULT NULL,
  `data_avaliacao` DATE NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idavaliacao`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `avaliacao_fisica_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `data_contratacao` DATE NOT NULL,
  `salario` DECIMAL(10,2) NULL DEFAULT NULL,
  `cargo_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `cargo_id` (`cargo_id` ASC) VISIBLE,
  CONSTRAINT `funcionario_ibfk_1`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `mydb`.`cargo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`avaliador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `funcionario_id` INT(11) NOT NULL,
  `especialidade` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `funcionario_id` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `avaliador_ibfk_1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `mydb`.`funcionario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`categoria_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria_produto` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cupom_desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cupom_desconto` (
  `idcupom` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `percentual_desconto` DECIMAL(5,2) NULL DEFAULT NULL,
  `valor_desconto` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_validade` DATE NULL DEFAULT NULL,
  `quantidade_uso` INT(11) NULL DEFAULT 1,
  `tipo` ENUM('percentual', 'fixo') NULL DEFAULT 'percentual',
  PRIMARY KEY (`idcupom`),
  UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`dieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dieta` (
  `iddieta` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`iddieta`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `dieta_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`refeicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`refeicao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dieta_id` INT(11) NOT NULL,
  `tipo` ENUM('Café da manhã', 'Lanche da manhã', 'Almoço', 'Lanche da tarde', 'Jantar', 'Ceia') NOT NULL,
  `horario` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `dieta_id` (`dieta_id` ASC) VISIBLE,
  CONSTRAINT `refeicao_ibfk_1`
    FOREIGN KEY (`dieta_id`)
    REFERENCES `mydb`.`dieta` (`iddieta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`dieta_alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dieta_alimento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `refeicao_id` INT(11) NOT NULL,
  `alimento_id` INT(11) NOT NULL,
  `quantidade` DECIMAL(6,2) NOT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `refeicao_id` (`refeicao_id` ASC) VISIBLE,
  INDEX `alimento_id` (`alimento_id` ASC) VISIBLE,
  CONSTRAINT `dieta_alimento_ibfk_1`
    FOREIGN KEY (`refeicao_id`)
    REFERENCES `mydb`.`refeicao` (`id`),
  CONSTRAINT `dieta_alimento_ibfk_2`
    FOREIGN KEY (`alimento_id`)
    REFERENCES `mydb`.`alimento` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NULL DEFAULT NULL,
  `funcionario_id` INT(11) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `rua` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `complemento` VARCHAR(50) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `funcionario_id` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `endereco_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`idusuario`),
  CONSTRAINT `endereco_ibfk_2`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `mydb`.`funcionario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`endereco_entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco_entrega` (
  `idendereco` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT(11) NOT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `rua` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `complemento` VARCHAR(50) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `endereco_entrega_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exercicio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `grupo_muscular` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `video_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`forum` (
  `idtopico` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idtopico`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `forum_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`treino` (
  `idtreino` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `horario` TIME NOT NULL,
  `descricao` TEXT NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idtreino`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `treino_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`historico_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historico_treino` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `treino_id` INT(11) NOT NULL,
  `data_execucao` DATETIME NOT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `treino_id` (`treino_id` ASC) VISIBLE,
  CONSTRAINT `historico_treino_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`idusuario`),
  CONSTRAINT `historico_treino_ibfk_2`
    FOREIGN KEY (`treino_id`)
    REFERENCES `mydb`.`treino` (`idtreino`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idpedido` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT(11) NOT NULL,
  `data_pedido` DATETIME NOT NULL,
  `status` ENUM('processando', 'enviado', 'concluído') NULL DEFAULT 'processando',
  PRIMARY KEY (`idpedido`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `pedido_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idproduto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `quantidade_estoque` INT(11) NOT NULL,
  `imagem` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_pedido` (
  `iditem` INT(11) NOT NULL AUTO_INCREMENT,
  `pedido_idpedido` INT(11) NOT NULL,
  `produto_idproduto` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`iditem`),
  INDEX `pedido_idpedido` (`pedido_idpedido` ASC) VISIBLE,
  INDEX `produto_idproduto` (`produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `item_pedido_ibfk_1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `mydb`.`pedido` (`idpedido`),
  CONSTRAINT `item_pedido_ibfk_2`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`meta_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`meta_usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `descricao` TEXT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_limite` DATE NULL DEFAULT NULL,
  `status` ENUM('ativa', 'concluída', 'cancelada') NULL DEFAULT 'ativa',
  PRIMARY KEY (`id`),
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `meta_usuario_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `idpagamento` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT(11) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `data_pagamento` DATETIME NOT NULL,
  `metodo` VARCHAR(45) NOT NULL,
  `status` ENUM('sucesso', 'falha', 'reembolsado') NULL DEFAULT 'sucesso',
  PRIMARY KEY (`idpagamento`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `pagamento_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento_detalhe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento_detalhe` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pagamento_idpagamento` INT(11) NOT NULL,
  `tipo` ENUM('cartao', 'pix', 'boleto') NOT NULL,
  `bandeira_cartao` VARCHAR(30) NULL DEFAULT NULL,
  `ultimos_digitos` VARCHAR(4) NULL DEFAULT NULL,
  `codigo_pix` VARCHAR(255) NULL DEFAULT NULL,
  `linha_digitavel_boleto` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `pagamento_idpagamento` (`pagamento_idpagamento` ASC) VISIBLE,
  CONSTRAINT `pagamento_detalhe_ibfk_1`
    FOREIGN KEY (`pagamento_idpagamento`)
    REFERENCES `mydb`.`pagamento` (`idpagamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plano` (
  `idplano` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `duracao` VARCHAR(45) NULL DEFAULT NULL,
  `assinatura_idassinatura` INT(11) NOT NULL,
  PRIMARY KEY (`idplano`),
  INDEX `assinatura_idassinatura` (`assinatura_idassinatura` ASC) VISIBLE,
  CONSTRAINT `plano_ibfk_1`
    FOREIGN KEY (`assinatura_idassinatura`)
    REFERENCES `mydb`.`assinatura` (`idassinatura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`resposta_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resposta_forum` (
  `idresposta` INT(11) NOT NULL AUTO_INCREMENT,
  `mensagem` TEXT NOT NULL,
  `data_resposta` DATETIME NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  `forum_idtopico` INT(11) NOT NULL,
  PRIMARY KEY (`idresposta`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `forum_idtopico` (`forum_idtopico` ASC) VISIBLE,
  CONSTRAINT `resposta_forum_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`),
  CONSTRAINT `resposta_forum_ibfk_2`
    FOREIGN KEY (`forum_idtopico`)
    REFERENCES `mydb`.`forum` (`idtopico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`treino_exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`treino_exercicio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `treino_id` INT(11) NOT NULL,
  `exercicio_id` INT(11) NOT NULL,
  `series` INT(11) NOT NULL,
  `repeticoes` INT(11) NOT NULL,
  `carga` DECIMAL(5,2) NULL DEFAULT NULL,
  `intervalo_segundos` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `treino_id` (`treino_id` ASC) VISIBLE,
  INDEX `exercicio_id` (`exercicio_id` ASC) VISIBLE,
  CONSTRAINT `treino_exercicio_ibfk_1`
    FOREIGN KEY (`treino_id`)
    REFERENCES `mydb`.`treino` (`idtreino`),
  CONSTRAINT `treino_exercicio_ibfk_2`
    FOREIGN KEY (`exercicio_id`)
    REFERENCES `mydb`.`exercicio` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
