-- MySQL Script generated by MySQL Workbench
-- qui 03 abr 2025 10:59:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,  -- Corrigido
  `foto_de_perfil` VARCHAR(100) NULL DEFAULT NULL,
  `numero_matricula` VARCHAR(20) NOT NULL,  -- Corrigido
  `tipo_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



-- -----------------------------------------------------
-- Table `mydb`.`assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`assinatura` (
  `idassinatura` INT(11) NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idassinatura`, `usuario_idusuario`),
  INDEX `fk_assinatura_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_assinatura_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao_fisica` (
  `idavaliacao` INT(11) NOT NULL AUTO_INCREMENT,
  `peso` DECIMAL(5,3) NOT NULL,
  `altura` DECIMAL(5,2) NOT NULL,
  `imc` DECIMAL(5,2) NOT NULL,
  `percentual_gordura` DECIMAL(5,2) NULL DEFAULT NULL,
  `data_avaliacao` DATE NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idavaliacao`, `usuario_idusuario`),
  INDEX `fk_avaliacao_fisica_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_fisica_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plano` (
  `idplano` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `duracao` VARCHAR(45) NULL DEFAULT NULL,
  `assinatura_idassinatura` INT(11) NOT NULL,
  PRIMARY KEY (`idplano`, `assinatura_idassinatura`),
  INDEX `fk_plano_assinatura1_idx` (`assinatura_idassinatura` ASC) VISIBLE,
  CONSTRAINT `fk_plano_assinatura1`
    FOREIGN KEY (`assinatura_idassinatura`)
    REFERENCES `mydb`.`assinatura` (`idassinatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`treino` (
  `idtreino` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `horario` TIME NOT NULL,
  `descricao` TEXT NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idtreino`, `usuario_idusuario`),
  INDEX `fk_treino_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_treino_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- DROP DATABASE mydb;

-- Inserindo um usuário
INSERT INTO `mydb`.`usuario` 
(`nome`, `senha`, `email`, `cpf`, `data_de_nascimento`, `telefone`, `foto_de_perfil`, `numero_matricula`, `tipo_usuario`) 
VALUES 
('João Silva', 'senha123', 'joao.silva@email.com', '123.456.789-00', '1990-05-20', 11999998888, 'joao.jpg', 2025001, 1);

-- Pegando o ID do usuário inserido (pode ser necessário se for fazer por script)
-- Supondo que seja o ID 1

-- Inserindo uma assinatura para o usuário
INSERT INTO `mydb`.`assinatura` 
(`data_inicio`, `data_fim`, `usuario_idusuario`) 
VALUES 
('2025-04-01', '2025-07-01', 1);

-- Supondo que o id da assinatura seja 1

-- Inserindo um plano associado à assinatura
INSERT INTO `mydb`.`plano` 
(`tipo`, `duracao`, `assinatura_idassinatura`) 
VALUES 
('Mensal', '3 meses', 1);

-- Inserindo uma avaliação física para o usuário
INSERT INTO `mydb`.`avaliacao_fisica` 
(`peso`, `altura`, `imc`, `percentual_gordura`, `data_avaliacao`, `usuario_idusuario`) 
VALUES 
(75.500, 1.75, 24.6, 15.50, '2025-04-01', 1);

-- Inserindo um treino para o usuário
INSERT INTO `mydb`.`treino` 
(`tipo`, `horario`, `descricao`, `usuario_idusuario`) 
VALUES 
('Musculação', '08:30:00', 'Treino de membros superiores: peito, bíceps e costas.', 1);
